### ISSUE TITLE
Add whitelist assumptions for every hook event

### ISSUE THREAD

**Issue by fiedlr** [runtimeverification/proof-checker#459]
Follow up of #458 .

# Intro 

Hook events provide results for various domain reasoning like basic arithmetic over integers for which we do not have explicit definitions.
Computations of these are delegated to the backend and  other tools for performance reasons. 

# Problem

Results of hook events will not be proved. Instead, we need to add for every such event an equality axiom of the form
```
hook(arg1, ..., argn) = result
```

where hook is a name of the domain function applied to arguments arg1...argn, equality is the notation from the definedness module, and result is given by the proof hint. 

This task adds these to Gamma and add simplification handling in the simplest form (top-level).

# Sketch of the solution

- [x] Add a `dv.k` test file and check that we can generate hints for the example.
- [x] Define a test semantics for the `dv.k` for further unit testing.
- [x] Add a function collect_whitelist_assumptions that will be similar to collect_functional_axioms. For every hook event of a rewrite step, it will be called and the assumptions added to axioms. This will be memorized to prevent duplicity.
- [x] Update the simplification Prover and Performer classes to generate proofs using new axioms.
- [x] Add a unit test with a rewrite step containing hook events and expected output for collect_functional_axioms
- [x] Update hints processing and add all new necessary classes to forward hook events to the Proof Expression class.
- [x] Add tests for hardwired hints trace for the `dv` example, as it is done for tree-reverse and simple-rewrite examples. We need to test that hints are processed correctly by the llvm hints parse and `get_proof_hints`
- [x] Add an integration test with a single rewrite doing a single addition and prove it with the added axiom.

Example of a trace with hook events (for `dv.k` and `succ(foo(5)))` rewritten to `foo(6)`:
```
Rule 2688 [label: N/A] [loc: 8,6] [substs: 3]
  Var'Unds'DotVar0 = [kore]
  Var'Unds'DotVar1 = [kore]
  VarX = [kore]
Hook: INT.add @ 0:0:0:0:0:0
  Function: Lbl'UndsPlus'Int'Unds'{} @ 0:0:0:0:0:0
    Term: [kore]
    Term: [kore]
  Result: [kore]
Config: [kore]
```

# The working branch

The work for subtasks marked finished above is in the `builtin-hooks` branch.

**Comment by IljaZakharov** [comment]
There are two PRs (#683 and #691) that implement the functionality in the issue.  But running the K file is still impossible because of the dependency on functional substitutions and proofs blown up in size. So it is proposed to create a separate issue for making running the integration test example with the K file.
