### ISSUE TITLE
Implement `ExecutionProofExp.prove_simplification` 

### ISSUE THREAD

**Issue by nishantjr** [runtimeverification/proof-checker#473]
1. Assume axiom `p1 k= p2 -> phi0[p1/x] k= phi0[p2/x]`
2. Define a function that proves:

   ```
           p1 k= p2
   -----------------------
   phi0[p1/x] k= phi0[p2/x]
   where $x$ is an `app_ctx_hole` in `phi0`.
   ```
*Sketch for 2.* Load the axiom given by 1. and apply MP.

3. Implement a method `prove_simplification`:

    ```
    def prove_simplification(ordinal, substitution, location: tuple[int]) -> ProofThunk
    ```

    that proves that the subterm of `ProofGenExp.current_config` at `location`
    can be simplified using the rule with ordinal `ordinal`.
    That is, suppose:

    * `ProofGenExp.current_config` is `<k> four(3) </k>`.
    * `location` is `(0)`, and
    * `ordinal` refers to the rule `four(I) = 4`

    Then the function `prove_simplification` returns the proof of `<k> four(3) </k> k= <k> 4 </k>`

*Sketch for 3.*
The function will use `SimplificationPerformer::update_subterm` function to plug a hole (element variable) into `loc = (0)` of `current_config`, this will be `phi0`. Then it will instantiate the equational rule given by `ordinal` with the given `substitution` to get `p1 := four(3)` (lhs of the equational ruile) and `p2 = 4` (rhs of the equational rule), and apply 2. with this `phi0` and `p1, p2`.

**Comment by fiedlr** [comment]
Temporarily closing, see https://runtimeverification.slack.com/archives/C05MF3KEWNM/p1702434023043889?thread_ts=1702297444.803519&cid=C05MF3KEWNM

The inductive solution seems easier to do than this approach.
