### ISSUE TITLE
Fix memoization by replacing parameric proofs with dynamic_inst where possible

### ISSUE THREAD

**Issue by fiedlr** [runtimeverification/proof-checker#699]
# Problem

The problem is that if you have a proof generation function like
```python
derived_rule(phi1) -> ProofThunk
```
that allows you to “pick” the pattern phi1 used inside, this breaks memoization, as it generates different proofs for different phi1.

# Solutions
a) Whenever possible, we should have

`derived_rule_pf() -> ProofThunk` where `phi1` is fixed in `derived_rule_pf`, and then instantiate `phi1` with the intended pattern like this:
```python
def derived_rule(phi1: Pattern) -> ProofThunk:
     return self.dynamic_inst(self.derived_rule_pf(), {1: phi1})
```

We can also have a decorator `@derived_rule` for this exact purpose. 
b) Or we can audit and enforce the convention to use `self.dynamic_inst` in parametric proofs themselves like this.

**Comment by nishantjr** [comment]
@fiedlr Lets make sure Issues are self contained.  Let's not link to slack messages.

**Comment by fiedlr** [comment]
> @fiedlr Lets make sure Issues are self contained. Let's not link to slack messages.

You're right, I added it in a hurry. will fix

**Comment by fiedlr** [comment]
@nishantjr I added the description of the actual problem.

**Comment by MirceaS** [comment]
@fiedlr @nishantjr 
Using a decorator or in general applying this technique mechanically everywhere is dangerous as I have found out.
If you have a lemma that takes in, say, both a `ProofThunk` as well as a `Pattern`, then, when doing a `dynamic_inst` we may accidentally also instantiate metavars occuring in the conclusion of the `ProofThunk` if we do end up having to use it.

**Comment by fiedlr** [comment]
@MirceaS Ok please then do it by hand where not dangerous

**Comment by MirceaS** [comment]
I did an audit of all the places we currently use Propositional lemmas for kore proof generation and it doesn't seem like we can apply the dynamic_inst optimization anywhere else.
