### ISSUE TITLE
Proposal: increasing memory width

### ISSUE THREAD

**Issue by fiedlr** [runtimeverification/proof-checker#706]
# Problem 

Right now, we can only use 256 memory locations because the `Load` instruction takes a single byte. This significantly decreases the number of possibilities to use memoization. Especially for projects like KEVM with huge configurations, it is essential we can reuse as many patterns and subproofs as we can.

# Possible solutions

## Overflowing Load

This choice is the easiest to implement. We'll have a single `Load` instruction that overflows on the `256` that will also indicate a next byte is needed, i.e.,:
```
Load 255
```
refers to location 255, and
```
Load 256 0
```
refers to 256
```
Load 256 256 1
```
refers to 513.

The advantage here is that for the common memory locations picked by `CountingInterpreter`, we will still use just one byte.

## Load taking a number of bytes

We can have a special extra instruction `WideLoad {n} {byte*n}` for the less commonly used memory locations bigger than 256 like this:

```
WideLoad 2 10 2 
```

There are many variants this could refer to. For example, it can refer to location `10 + 2` or `10 * 2^1 + 2 * 2^0`.  

## Combination of the previous methods

We can actually use different loads for different representations depending on which one uses the least amount of bytes for the given number.
For example, we could have a `ByteLoad 2 3 0`  that refers to location `2^3 + 2^0`, which on numbers like `2^4 - 1 = 2^3 + 2^2 + 2^1 + 2^0` would be quite inefficient but is very efficient for powers of two.

# My proposal

I would prefer solving this with the first solution `Overflowing Loads` as it is very simple. We can always add extra instructions for different representations "optimal" for different numbers if it turns out that we need bigger numbers.

**Comment by dwightguth** [comment]
I would recommend just replacing every one byte immediate with two bytes. You're going to need to be able to support more than 256 symbols too.

**Comment by fiedlr** [comment]
@dwightguth You mean that the first byte would be representing the digits 2^15, ..., 2^8 and the second byte would be representing 2^7 ... 2^0 like this:
```
Load 3 1
```
is referring to 2^(1 + 8) + 2^(0 + 8) given by the first byte + 2^(0) given by the second byte = 769

You're right, that actually sounds pretty good.

**Comment by dwightguth** [comment]
I mean, kinda, but you're missing the point. I'm saying just make it a two byte width address space, for a total of 65536 locations, from `LOAD 0` to `LOAD 65535`.

Whether you make it big endian or little endian doesn't really matter as long as you consistently pick one and use it throughout. I suggest little endian because that's the machine order on most modern processors.

**Comment by nishantjr** [comment]
The other decision to make is whether to use 2 byte words for instructions
as well. For native architectures being word-aligned may make a significant
difference. With Risc0 all bets are off of course.

**Comment by bmmoore** [comment]
Note the "overflow" idea has poor asymptotics, at even 4*256 uniformly accessed locations it's more expensive than just going to two bytes. From a ZK circuit point of view the smallest unit of data is a field element anyway, so with anything more custom than Risc0 any scheme chosen here will be decoded back to a single big number before the expensive crypto stuff starts.

**Comment by fiedlr** [comment]
> I mean, kinda, but you're missing the point. I'm saying just make it a two byte width address space, for a total of 65536 locations, from `LOAD 0` to `LOAD 65535`.
> 
> Whether you make it big endian or little endian doesn't really matter as long as you consistently pick one and use it throughout. I suggest little endian because that's the machine order on most modern processors.

@dwightguth I see now where our misunderstanding is coming from. The issue is we cannot "just" go up to two byte width because we are relying on R0 implementation of `FdReader`:
https://docs.rs/risc0-zkvm/latest/risc0_zkvm/guest/env/struct.FdReader.html

Right now, we are specifically using `read_to_end` that works with `Vector<u8>`. That's why I suggested adding an  explicit additional byte.

This input handling is far from ideal, but we are limited by the interface. Since you have lots of expertise in this, maybe you could take a look how to get around it?

**Comment by fiedlr** [comment]
> Note the "overflow" idea has poor asymptotics, at even 4*256 uniformly accessed locations it's more expensive than just going to two bytes. From a ZK circuit point of view the smallest unit of data is a field element anyway, so with anything more custom than Risc0 any scheme chosen here will be decoded back to a single big number before the expensive crypto stuff starts.

Yes, the asymptotics is poor. You guys are right, we shouldn't burn too much time on this and simply increase the address width.
